### ISSUE TITLE
二维码支付Connection reset

### ISSUE THREAD

**Issue by Bluebang** [egzosn/pay-java-parent#10]
![qq 20180206102650](https://user-images.githubusercontent.com/22443960/35838876-6b0eba22-0b28-11e8-9e49-0c7e179e629c.png)

沙箱环境在支付一次之后无法正常调用二维码了，一直出Connection reset。必须重启项目才行，请问这个是配置问题还是什么问题呢？

**Comment by Bluebang** [comment]
启动项目，访问二维码，然后等几分钟访问也会出现这样的情况

**Comment by egzosn** [comment]
你在用我的demo的时候也会出现这个问题吗？这个问题出现比较多种原因。

**Comment by Bluebang** [comment]
我是用wiki里面的快速入门那段代码测试的。可以分析一下都有哪些原因吗？

**Comment by egzosn** [comment]
最大的原因是你的网络问题导致的。你那边网络是否稳定，是否有东西被拦截等等

**Comment by Bluebang** [comment]
。。。这锅甩得，666

**Comment by egzosn** [comment]
什么鬼，你查下就知道了，遇到这种连接出问题的，本来就是网络或者连接数问题，我也没有摔锅的意思，我也清楚你那边网络什么情况，https的请求被拦截(抓包)也是一样的这样的问题，如果你觉得是我框架问题的话，那你可以让别人试试，这个框架我自己的公司也是经历了快两年的风雨了，使用者也不止你一个人吧，

**Comment by Bluebang** [comment]
我在一楼已经说了：启动项目第一次访问正常，如果中途没有访问，等几分钟再访问就一直被重置。这明显是你HttpClients的问题，这还能怪网络，这网络也还真实智能啊，专门拦截你库的请求不拦截DefaultAlipayClient的请求。我只是反应我遇到的问题，你要是觉得你的代码没问题，那就算了。

**Comment by egzosn** [comment]
可能是 httpclinet端缓存链接  失效管理和重发管理，我这边排查下吧。是在回调后出现这个问题还是在回调前就有了。我需要记录下这个问题，
