### ISSUE TITLE
paypal v2 ordersCapture请求时缺少请求头导致capture失败

### ISSUE THREAD

**Issue by coffee-developer** [egzosn/pay-java-parent#100]
当没有请求头时capture失败,UNSUPPORTED_MEDIA_TYPE
![image](https://github.com/egzosn/pay-java-parent/assets/35052485/a48ec994-d242-4671-8cfe-cab30a5bc6dc)
但加上Content-Type: application/json时capture就成功了
![image](https://github.com/egzosn/pay-java-parent/assets/35052485/9d5a23bd-2da0-4e2b-9808-5033c9695907)
paypal的接口文档也是说明需要指定Content-Type: application/json的
![image](https://github.com/egzosn/pay-java-parent/assets/35052485/ad8c8bdd-1e21-4953-a3a4-f5636b439a18)

**Comment by coffee-developer** [comment]
<dependency>
            <groupId>com.egzosn</groupId>
            <artifactId>pay-java-paypal</artifactId>
            <version>2.14.5</version>
        </dependency>

**Comment by egzosn** [comment]
收到

**Comment by egzosn** [comment]
查看最新版本
