### ISSUE TITLE
微信支付设置过期时间问题

### ISSUE THREAD

**Issue by Lilaccoral** [egzosn/pay-java-parent#18]
微信支付开发文档描述：
订单失效时间，格式为yyyyMMddHHmmss，如2009年12月27日9点10分10秒表示为20091227091010。

 com.egzosn.pay.wx.api.WxPayService
59    private final static DateFormat df = new SimpleDateFormat("yyyyMMddHHmms");
这个时间格式会导致如果过期时间的秒位是0-9，时间格式不合法，无法生成二维码，，，

**Comment by egzosn** [comment]
感谢，BUG已修复

**Comment by Lilaccoral** [comment]
大佬辛苦😁
