### ISSUE TITLE
微信退款 证书都设置了怎么会提示这个 支付错误: errcode=IOException, errmsg=api.mch.weixin.qq.com:443 failed to respond

### ISSUE THREAD

**Issue by 617450941** [egzosn/pay-java-parent#24]
支付错误: errcode=IOException, errmsg=api.mch.weixin.qq.com:443 failed to respond

        WxPayConfigStorage wxPayConfigStorage = new WxPayConfigStorage();
        wxPayConfigStorage.setMchId(mchid);
        wxPayConfigStorage.setAppid(appid);
        wxPayConfigStorage.setSecretKey(machKey);
        wxPayConfigStorage.setSignType("HMAC-SHA256");
        wxPayConfigStorage.setInputCharset("utf-8");
        HttpConfigStorage httpConfigStorage = new HttpConfigStorage();
        httpConfigStorage.setKeystore("MIIEvwI.......");
        httpConfigStorage.setStorePassword("1218......");

        httpConfigStorage.setPath(false);
        WxPayService service = new WxPayService(wxPayConfigStorage, httpConfigStorage);
        RefundOrder order = new RefundOrder("420000....", "", new BigDecimal(0.01), new BigDecimal(0.01));
        order.setRefundNo("zsdopadopasd123");
        Map result = service.refund(order);

**Comment by egzosn** [comment]
你ssl证书没有设置，请认真阅读微信的开发文档再进行接入

**Comment by 617450941** [comment]
@egaon  看我代码已经按文档设置了证书 但是就是报这个错误

**Comment by egzosn** [comment]
你ssl证书，是那样设置的么。证书文件来着，你看下pay-java的证书设置相关文档吧。3种方式：流的方式，流字符，证书文件绝对路径。

**Comment by 617450941** [comment]
都试了 不行  这个在spring boot怎么设置路径 路径换了几个都搞不了

**Comment by egzosn** [comment]
第一种方式 流的形式： InputStream resourceAsStream = this.getClass().getResourceAsStream("相对路径，根据你class来说");

第二种方式：自己编写一个脚本，然后文件上传，保存到数据库里面，数据库里面用varchar存储起来，同理取出的时候用String去取

**Comment by 617450941** [comment]
支持读取出证书里面的字符串内容直接放进去是吗?

**Comment by 617450941** [comment]
httpConfigStorage.setKeystore(getClass().getClassLoader().getResourceAsStream("certificate/apiclient_key.pem"));  

这样吗?  第一次写java微信支付

**Comment by 617450941** [comment]
还是报相同的错误
Request processing failed; nested exception is com.egzosn.pay.common.exception.PayErrorException: 支付错误: errcode=IOException, errmsg=api.mch.weixin.qq.com:443 failed to respond

**Comment by egzosn** [comment]
你是看不懂我上一个说的吗，可以直接设置流的方式，第三次跟你提到了。

-----------------------------------------------------------------------
 InputStream inputStream  = getClass().getResourceAsStream("certificate/apiclient_key.pem");

    WxPayConfigStorage wxPayConfigStorage = new WxPayConfigStorage();
    wxPayConfigStorage.setMchId(mchid);
    wxPayConfigStorage.setAppid(appid);
    wxPayConfigStorage.setSecretKey(machKey);
    wxPayConfigStorage.setSignType("MD5");
    wxPayConfigStorage.setInputCharset("utf-8");
    HttpConfigStorage httpConfigStorage = new HttpConfigStorage();
    httpConfigStorage.setKeystore(inputStream);
    httpConfigStorage.setStorePassword("1218523333");
    httpConfigStorage.setPath(false);
    WxPayService service = new WxPayService(wxPayConfigStorage, httpConfigStorage);
    RefundOrder order = new RefundOrder("420000027720190307559588123", "", new BigDecimal(0.01), new BigDecimal(0.01));
    order.setRefundNo("zsdopadopasd123");
    Map result = service.refund(order);

**Comment by 617450941** [comment]
![image](https://user-images.githubusercontent.com/7607957/54012359-c5cb5f00-41b0-11e9-82d6-84e8c189fcbb.png)

**Comment by 617450941** [comment]
已经是流的形式了 一样的

**Comment by egzosn** [comment]
突然看到，你的证书错了，pem的是PHP的，不是java的，java是pkcs12格式

**Comment by 617450941** [comment]
.p12的文件是吗

**Comment by egzosn** [comment]
是的，。
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=4_3

**Comment by 617450941** [comment]
可以了谢谢 没想到是这个问题

**Comment by egzosn** [comment]
解决了就好，如果你觉得项目对你有一定的帮助，你可以Star进行关注，项目会持续更新，也希望你能够提出项目的不足或者push你的优化

**Comment by 617450941** [comment]
问个问题 为什么企业付款到零钱一直提示 参数错误：必须填入商户号
代码如下：
        String outNo = RandomUtil.randomStr(32);

        WxPayConfigStorage wxPayConfigStorage = new WxPayConfigStorage();
        wxPayConfigStorage.setMchId(mchid);
        wxPayConfigStorage.setAppid(appid);
        wxPayConfigStorage.setSecretKey(machKey);
        wxPayConfigStorage.setKeyPublic(machKey);
        wxPayConfigStorage.setSignType("MD5");
        wxPayConfigStorage.setInputCharset("utf-8");
        WxPayService service = new WxPayService(wxPayConfigStorage);

        TransferOrder order = new TransferOrder();
        order.setOutNo(outNo);
        order.setPayeeAccount(res.getOpenId());
        order.setPayeeName(res.getName());
        order.setRemark("付款");
        order.setAmount(res.getAmount());
        order.setTransferType(WxTransferType.TRANSFERS);
        Map result = service.transfer(order);

**Comment by 617450941** [comment]
![image](https://user-images.githubusercontent.com/7607957/54115513-8ce8ef80-4427-11e9-94cd-5ab7f1928c04.png)
这里是不是有bug 已经按照文档设置了参数  但是断点获取到的payConfigStorage对象里面的参数都是null

**Comment by 617450941** [comment]
最后看了下是mch_id参数有误 微信官方文档是
![image](https://user-images.githubusercontent.com/7607957/54118914-164ff000-442f-11e9-9ad4-da5c43978ca7.png)


这个库里提交的商户号参数是这个
![image](https://user-images.githubusercontent.com/7607957/54118891-09cb9780-442f-11e9-895b-9eac095b8087.png)

**Comment by egzosn** [comment]
2.12.7版本已经发布，对这个参数问题已经修复
