### ISSUE TITLE
企业付款api商户号参数有bug

### ISSUE THREAD

**Issue by 617450941** [egzosn/pay-java-parent#25]
最后看了下是mch_id参数有误 并且没有可以供设置提现ip的方法 这个接口必须要传递ip参数 微信官方文档是
![image](https://user-images.githubusercontent.com/7607957/54119155-a5f59e80-442f-11e9-85fb-d801ccb88cd7.png)
![image](https://user-images.githubusercontent.com/7607957/54119165-ac841600-442f-11e9-8867-45393bad0b5f.png)

这个库里提交的商户号参数是这个
![image](https://user-images.githubusercontent.com/7607957/54119260-e0f7d200-442f-11e9-93b9-d568aa325cfa.png)

mchid 和 mch_id 作者这个库里多了个_

**Comment by egzosn** [comment]
代码已经提交了，版本发布可能没有那么快。

**Comment by 617450941** [comment]
那个设置ip的参数有了吗

**Comment by egzosn** [comment]
代码已经有提交的，ip也是有的。将在2.12.7中体现。

617450941 <notifications@github.com> 于 2019年3月12日周二 13:18写道：
