### ISSUE TITLE
Util部分JAVA源文件版权都没有移除

### ISSUE THREAD

**Issue by yooong** [egzosn/pay-java-parent#33]
![image](https://user-images.githubusercontent.com/12774500/56879788-dbf8eb80-6a8c-11e9-920d-9b7f5a1f8c7a.png)

**Comment by egzosn** [comment]
这个东西是从银联sdk那边直接拷贝过来的，所以就没有移除了。

**Comment by egzosn** [comment]
从java1.8中拷贝过来，所以保留原有版本信息.
