### ISSUE TITLE
支付宝APP支付 使用RSA2签名错误

### ISSUE THREAD

**Issue by RayChouGitHub** [egzosn/pay-java-parent#36]
调用APP支付组装信息 app端使用sdk调用支付宝支付，返回系统繁忙错误

问题：用官方sdk会存在一个参数alipay_sdk 但使用作者的没有 是不是这个原因引起的？？？ 我把现有签名串与官方工具签名对比结果一致 但还是出现签名错误，望大手解答

错误信息：
{\"alipay_trade_app_pay_response\":{\"code\":\"40002\",\"msg\":\"Invalid Arguments\",\"sub_code\":\"isv.invalid-signature\",\"sub_msg\":\"验签出错，建议检查签名字符串或签名私钥与应用公钥是否匹配，网关生成的验签字符串为：app_id=2017051607253746&biz_content={"body":"私人订单","out_trade_no":"8a12595241b6479c9ed9d4d1649310b4","product_code":"QUICK_MSECURITY_PAY","seller_id":"2088621830719584","subject":"私人订单单","total_amount":"0.03"}&charset=utf-8&format=json&method=alipay.trade.app.pay&notify_url=https:\\/\\/customer-beta.emeik.cn\\/api\\/customer\\/ali_pay\\/app\\/notify\\/down_payment&return_url=&sign_type=RSA2&timestamp=2019-05-09 18:04:33&version=1.0\"}}

**Comment by egzosn** [comment]
详情查看，https://gitee.com/egzosn/pay-java-parent/issues/IWDU4
