### ISSUE TITLE
银联支付初始化时空指针

### ISSUE THREAD

**Issue by xjh1994** [egzosn/pay-java-parent#38]
```
UnionPayConfigStorage unionPayConfigStorage = buildUnionPayConfig();
PayService service = new UnionPayService(unionPayConfigStorage);
```

new UnionPayService的时候空指针，在截图的85行。
除非设置 `unionPayConfigStorage.setCertSign(false);` 才不会走到这行初始化。但是证书签名设置为false以后，下单的接口里面又调用的证书相关的代码，又报了空指针……

![image](https://user-images.githubusercontent.com/3397116/57618559-61fd5200-75b6-11e9-9198-6e54dedb64bb.png)

完全按照文档操作的，不知道哪边出错了。有空请告知，感谢！

**Comment by xjh1994** [comment]
问题应该是`UnionPayService`对象的初始化顺序有问题，在父类`BasePayService`构造函数中调用了子类`UnionPayService`的`setPayConfigStorage`方法，方法中调用了此时还未初始化的`certDescriptor`变量

**Comment by egzosn** [comment]
赞，就是这个问题

**Comment by egzosn** [comment]
在2.12.8中进行多次测试已经可以正常使用，如果某些还会出现这个问题，那么接下来将对其不在使用setPayConfigStorage方法
