### ISSUE TITLE
启动demo报错，请问是什么原因

### ISSUE THREAD

**Issue by kleen** [egzosn/pay-java-parent#4]
![image](https://cloud.githubusercontent.com/assets/3284413/25232571/67ba6b3c-260e-11e7-910d-8ec45218204e.png)

**Comment by egzosn** [comment]
编译的时候编码类型不一致。你找到这一串来
 <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
                <source>1.7</source>
                <target>1.7</target>
           </configuration>
 </plugin>
然后加上
   <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
                <source>1.7</source>
                <target>1.7</target>
                <encoding>UTF-8</encoding>
            </configuration>
        </plugin>
