### ISSUE TITLE
支付请求连接超时设置？优化

### ISSUE THREAD

**Issue by sosowei** [egzosn/pay-java-parent#40]
是否考虑增加超时设置
CloseableHttpClient httpClient = HttpClients
                .custom()
                //网络提供者
                .setDefaultCredentialsProvider(createCredentialsProvider(configStorage))
                //设置httpclient的SSLSocketFactory
                .setSSLSocketFactory(createSSL(configStorage))
                .setConnectionManager(connectionManager(configStorage))
                **.setDefaultRequestConfig(createRequestConfig(configStorage))**
                .build();

**RequestConfig createRequestConfig(HttpConfigStorage configStorage){
        //设置请求和传输超时时间
        // setConnectionRequestTimeout 设置从connect Manager(连接池)获取Connection 超时时间，单位毫秒。这个属性是新加的属性，因为目前版本是可以共享连接池的。
        RequestConfig requestConfig = RequestConfig.custom()
                .setSocketTimeout(configStorage.getSocketTimeout())
                .setConnectTimeout(configStorage.getConnectTimeout())
//                .setConnectionRequestTimeout(1000)
                .build();
        return requestConfig;
    }**

**Comment by egzosn** [comment]
2.12.8中已经对其添加，感谢
