### ISSUE TITLE
IntelliJ IDEA下怎么运行demo

### ISSUE THREAD

**Issue by handsomeyang** [egzosn/pay-java-parent#41]

**Comment by egzosn** [comment]
运行方式有很多种，你可以直接看maven的插件，已经在里面提供好tomcat的，可直接运行

**Comment by handsomeyang** [comment]
maven deploy出现错误：
`[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.3:deploy (injected-nexus-deploy) on project pay-java-demo: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.3:deploy failed: Server credentials with ID "ossrh" not found! -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
`

**Comment by egzosn** [comment]
为啥你会用maven deploy 这个命令呢，如果你对maven不了解的话，你可以先学习下maven
