### ISSUE TITLE
orderInfo方法返回的微信JSAPI支付参数不对

### ISSUE THREAD

**Issue by jjyyjjyy** [egzosn/pay-java-parent#43]
[文档地址](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=7_7&index=6)

应该是 `paySign` , 而不是 `sign`

`timeStamp` 字段值应该为字符串, 否则iOS微信内支付会报 `调用支付jsapi缺少参数: timeStamp` 错误.

**Comment by egzosn** [comment]
这个东西：“sign”只是暂时存放。需要前端自行更正，签名是完全正确的，然后至于timeStamp的问题也是需要前端自行处理的
