### ISSUE TITLE
payonner的API是需要开通批量支付吗

### ISSUE THREAD

**Issue by 843901020** [egzosn/pay-java-parent#46]
官网并没有有关API的内容
        configStorage.setUserName("PayoneerPay 用户名");
        configStorage.setApiPassword("PayoneerPay API password");
 其中的UserName和Password是哪里能够找到
请问这个批量支付开通有没有什么要求/如何开通
十分感谢

**Comment by egzosn** [comment]
payonner 审核比较严格，需要有专门的市场经理进行对接的

**Comment by 843901020** [comment]
十分感谢
