### ISSUE TITLE
Fastjson 问题

### ISSUE THREAD

**Issue by Alaske** [egzosn/pay-java-parent#50]
can not get javaBeanDeserializer. com.alibaba.fastjson.JSONObject

JsonObject.toJavaObject(T(JSONObject)) 导致解析出错

**Comment by egzosn** [comment]
你能否给全一些的日志，

**Comment by egzosn** [comment]
1.使用的pay-java的版本是多少？
2.你的fastjson版本可能没有对应上

**Comment by egzosn** [comment]
如果没什么问题我就先关了。
