### ISSUE TITLE
DateUtils#minutesRemaining

### ISSUE THREAD

**Issue by bravemay** [egzosn/pay-java-parent#51]
这个工具类，因为订单到支付会有那么几秒的时间差，因此直接算超时时间的话会导致支付宝订单超时时间少了一分钟。
`        if (null != order.getExpirationTime()) {
            long round = Math.round((order.getExpirationTime().getTime() - System.currentTimeMillis()) / 1000d / 60);
            bizContent.put("timeout_express", round + "m");
        }`

**Comment by egzosn** [comment]
感谢，后续版本会进行优化修复
