### ISSUE TITLE
微信沙箱环境退款报错

### ISSUE THREAD

**Issue by zt1820057934** [egzosn/pay-java-parent#53]
<img width="1104" alt="截屏2020-04-01下午3 08 07" src="https://user-images.githubusercontent.com/31762662/78108756-9a09bf80-742a-11ea-9aee-3aedb09bc815.png">
<img width="780" alt="截屏2020-04-01下午3 08 42" src="https://user-images.githubusercontent.com/31762662/78108827-b0b01680-742a-11ea-983d-3ab4cac340e0.png">
你好， 用你的工具包，微信支付在沙箱环境调好了， 但 退款报错， 沙箱环境也得需要证书吗？ 我没弄证书,准确来说现在弄不到证书，不是不想弄

**Comment by egzosn** [comment]
都是需要的，你可以用生产环境去测试吧

**Comment by zt1820057934** [comment]
谢谢，需要的话就明白为啥报错了，  我们项目现在拿不到更多微信需要的东西，之后再说
