### ISSUE TITLE
app支付，回调域名带有- 横杠 会导致alin10146

### ISSUE THREAD

**Issue by jol5** [egzosn/pay-java-parent#56]
1.回调地址，如  a-admin.xxxx.com，唤起支付宝，报错。
解决：域名去除-,也就是aadmin.xxxx.com正常唤起支付。

**Comment by egzosn** [comment]
APP支付吗

**Comment by jol5** [comment]
是的，APP 支付&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "egan"<notifications@github.com&gt;; 
发送时间: 2020年5月26日(星期二) 中午11:17
收件人: "egzosn/pay-java-parent"<pay-java-parent@noreply.github.com&gt;; 
抄送: "Jol."<790860872@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [egzosn/pay-java-parent] app支付，回调域名带有- 横杠 会导致alin10146 (#56)





 
APP支付吗

**Comment by egzosn** [comment]
我在想是不是支付宝不支持

**Comment by jol5** [comment]
> 我在想是不是支付宝不支持

**Comment by jol5** [comment]
> 我在想是不是支付宝不支持

点错了，给关闭了。。感觉像支付宝不支持。这个真没想到，加个  -  死活付不了款，哈哈。
