### ISSUE TITLE
微信退款不支持自定义参数，可选参数无法使用

### ISSUE THREAD

**Issue by kamjin1996** [egzosn/pay-java-parent#60]
支付宝退款：alipay.trade.refund(统一收单交易退款接口)

这个接口里，我想使用里面的参数：query_options，传一个"refund_detail_item_list"

但看了下refund方法，没看到该参数的传入，想通过重写AliPayService的方法达到目的，但是里面各种方法，都是私有的，包括Map类型的bizContent也是局部变量，这样就无法传入哪些可选但某些情况下有用的参数了

可以考虑新增一个接口专门用来参数拓展吗，类似参数后置处理的方式
或者别的方式，比如将sevice支持定制（重写）的内容，抽象至abstractPay，方法修饰符为protected，一些特定的，默认的 用defaultPayService来实现，这样一来就可自行实现，选择性的进行定制service的组成

还有就是，微信的退款回调 我想回调另外一个地址，因为逻辑放一起太混乱了，我看微信payService的refund方法里，是直接获取原先配置的notifyUrl了，这样我就没法自定义其他notifyUrl了，不知道可否支持自定义一下？

2.13.2版本 微信退款无法自定义参数 方法实现里没使用到attr

**Comment by egzosn** [comment]
赞

**Comment by egzosn** [comment]
2.13.2已经提交，已提供附加参数的时候方式
