### ISSUE TITLE
微信支付两个问题

### ISSUE THREAD

**Issue by yuegongzi** [egzosn/pay-java-parent#63]
JSAPI情况下
返回的参数key是 "sign" 实际应为paySign 否则就要自己前端转一下,
沙盒测试一直报错xml格式不正确, 将请求的xml 自己写http请求就没问题,排除组装的问题,怀疑是不是http工具类哪里处理有问题

**Comment by egzosn** [comment]
1.返回的参数key是 "sign" 实际应为paySign 否则就要自己前端转一下,  这个自己前端转一下
2.沙盒测试一直报错xml格式不正确  这个已修复，暂没有同步到github

**Comment by egzosn** [comment]
2.13.3版本已经发布，已修复该问题
