### ISSUE TITLE
支付宝公钥证书 verify 报错 

### ISSUE THREAD

**Issue by hexw** [egzosn/pay-java-parent#66]
需要过滤掉返回alipay_cert_sn
![QQ截图20201227201314](https://user-images.githubusercontent.com/3970924/103170572-1cbb9000-4880-11eb-9a5e-bce90da711c8.png)

**Comment by hexw** [comment]
signVerify 方法
if (SIGN.equals(entry.getKey())) {
                    continue;
                }
                if ("alipay_cert_sn".equals(entry.getKey())) {
                    continue;
                }

**Comment by hexw** [comment]
AliPayService 里面的setSign getPublicParameters loadCertSn setAppAuthToken getKeyPublic 能改成protected吗方便扩展

**Comment by egzosn** [comment]
收到，近期会进行修复，感谢，并提供尽量做到更为灵活

**Comment by egzosn** [comment]
已修复
