### ISSUE TITLE
微信查询企业付款接口实现错误

### ISSUE THREAD

**Issue by 99246255** [egzosn/pay-java-parent#67]
WxPayService.transferQuery 实现错误
```
public Map<String, Object> transferQuery(String outNo, String wxTransferType) {
        Map<String, Object> parameters = new TreeMap();
        parameters.put("mch_id", ((WxPayConfigStorage)this.payConfigStorage).getPid());
        parameters.put("partner_trade_no", outNo);
        parameters.put("nonce_str", SignUtils.randomStr());
        parameters.put("sign", this.createSign(SignUtils.parameterText(parameters, "&", new String[]{"sign"}), ((WxPayConfigStorage)this.payConfigStorage).getInputCharset()));
        if (StringUtils.isEmpty(wxTransferType)) {
            throw new PayErrorException(new WxPayError("failure", "微信转账类型 #transferQuery(String outNo, String wxTransferType) 必填，详情com.egzosn.pay.wx.bean.WxTransferType"));
        } else {
            return !WxTransferType.TRANSFERS.getType().equals(wxTransferType) && !WxTransferType.GETTRANSFERINFO.getType().equals(wxTransferType) ? (Map)this.getHttpRequestTemplate().postForObject(this.getReqUrl(WxTransferType.QUERY_BANK), XML.getMap2Xml(parameters), JSONObject.class, new Object[0]) : (Map)this.getHttpRequestTemplate().postForObject(this.getReqUrl(WxTransferType.GETTRANSFERINFO), XML.getMap2Xml(parameters), JSONObject.class, new Object[0]);
        }
    }
```
微信查询企业付款接口，https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_3
service.transferQuery("XXX", WxTransferType.GETTRANSFERINFO.name());

```
<xml>
<return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[参数错误:必须输入appid]]></return_msg>
<result_code><![CDATA[FAIL]]></result_code>
<err_code><![CDATA[PARAM_ERROR]]></err_code>
<err_code_des><![CDATA[参数错误:必须输入appid]]></err_code_des>
</xml>
```

**Comment by egzosn** [comment]
文档没有说明nonce_str 是转账支付完成之后返回参数吧，你在进行查询的时候返回什么异常信息，能否提供一下，或者能否说下你是怎么进行矫正的

**Comment by 99246255** [comment]
> 
> 
> 文档没有说明nonce_str 是转账支付完成之后返回参数吧，你在进行查询的时候返回什么异常信息，能否提供一下，或者能否说下你是怎么进行矫正的
service.transferQuery("XXXX", WxTransferType.GETTRANSFERINFO.name());
后来看了下好像确实这个参数可以是随机的，但是缺少appId 
<xml>
<return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[参数错误:必须输入appid]]></return_msg>
<result_code><![CDATA[FAIL]]></result_code>
<err_code><![CDATA[PARAM_ERROR]]></err_code>
<err_code_des><![CDATA[参数错误:必须输入appid]]></err_code_des>
</xml>

**Comment by egzosn** [comment]
你在配置的时候没有设置appid嘛，
![图片](https://user-images.githubusercontent.com/19421296/109608723-438a9100-7b65-11eb-97c4-36963793f855.png)

**Comment by 99246255** [comment]
> 
> 
> 你在配置的时候没有设置appid嘛，
> ![图片](https://user-images.githubusercontent.com/19421296/109608723-438a9100-7b65-11eb-97c4-36963793f855.png)

单元测试如下

`		public static void main(String[] args) {
			WxPayConfigStorage wxPayConfigStorage = new WxPayConfigStorageExt();
			wxPayConfigStorage.setMchId("XXX");
			wxPayConfigStorage.setAppid("XXX");
			wxPayConfigStorage.setKeyPrivate("XXX");
			wxPayConfigStorage.setKeyPublic("XXX");
			wxPayConfigStorage.setPayType("wxPay");
			wxPayConfigStorage.setSignType("MD5");
			wxPayConfigStorage.setInputCharset("utf-8");

			HttpConfigStorage httpConfigStorage = new HttpConfigStorage();
			httpConfigStorage.setStorePassword("XX");
			String certPath = "XXX";
			httpConfigStorage.setKeystore(certPath);
			//设置ssl证书对应的存储方式输入流，这里默认为文件地址
			httpConfigStorage.setCertStoreType(CertStoreType.PATH);
			WxPayService service = new WxPayService(wxPayConfigStorage, httpConfigStorage);
			Map<String, Object> map = service.transferQuery("XXX", WxTransferType.GETTRANSFERINFO.name());
	}`

**Comment by egzosn** [comment]
对不住，只实现了转账到卡的实现

**Comment by egzosn** [comment]
之前已经修复，关闭
