### ISSUE TITLE
getSecretKey报错问题

### ISSUE THREAD

**Issue by s19870620i** [egzosn/pay-java-parent#7]
您好，pay-java-ali项目，有继承方法：com.egzosn.pay.ali.api.AliPayConfigStorage.getSecretKey()，但是这个方法在deprecated类com.egzosn.pay.common.before.api.PayConfigStorage，请问怎么处理这个报错问题呀？

**Comment by egzosn** [comment]
真心对不起，版本移除的时候遗漏了，已提交请更新后使用
