### ISSUE TITLE
支付发起的结果问题

### ISSUE THREAD

**Issue by GabbyMrH** [egzosn/pay-java-parent#78]
请教作者一个问题：发起支付的代码示例只看到了
```
        // 获取支付所需的信息
        Map<String, Object> directOrderInfo = aliPayService.orderInfo(payOrder);
        //获取表单提交对应的字符串，将其序列化到页面即可,
        String directHtml = aliPayService.buildRequest(directOrderInfo, MethodType.POST)
```
这样的代码，按照文档是直接返回页面，但是如果我想知道支付调取成功或者失败的结果，如何得知？比如支付宝官方文档是这样获取的：
```
request.setBizContent(bizContent.toString());
AlipayTradeWapPayResponse response = alipayClient.pageExecute(request);
if(response.isSuccess()){
System.out.println("调用成功");
} else {
System.out.println("调用失败");
}
```
请问咱们这边如何获取呢？

**Comment by egzosn** [comment]
这个你得去了解支付流程了，这里我就不细说了，你去看看支付宝网页支付接入流程

**Comment by GabbyMrH** [comment]
您这边可能还没明白我意思，不是流程明不明白的问题。是你的sdk发起支付时如何得知支付宝那边成功返回了？向支付平台发起支付，那支付平台是会返回对应状态码，一般以此来判断发起成功与否是不？但是我在您的sdk并没有看到呢，而是发起之后后直接就返回directHtml了。

**Comment by GabbyMrH** [comment]
顺带贴一张支付流程图吧：
![image](https://user-images.githubusercontent.com/30254530/139617869-65b3cd07-d974-4a7d-bf1f-3340dec08962.png)

**Comment by egzosn** [comment]
解答有点晚了，
![图片](https://user-images.githubusercontent.com/19421296/159171103-20905e4b-8e95-46e1-a0b2-23b67bdf329c.png)
你说的【如果我发起失败了】会返回html，那你可以用一下就知道了，支付宝网页支付根本就没有像微信那种预订单的概念，在支付宝这边生成的网页就是用来发起支付的(这里并且生产预订单)
