### ISSUE TITLE
请问这里设置证书setApiClientKeyP12一直报如下错如何解决

### ISSUE THREAD

**Issue by bnyte** [egzosn/pay-java-parent#80]
支付错误: errcode=failure, errmsg= keystore 初始化失败
![Uploading image.png…]()

**Comment by bnyte** [comment]
![image](https://user-images.githubusercontent.com/75556346/141647032-fda58be9-d1f4-434f-944d-3d4ba6566afc.png)

**Comment by egzosn** [comment]
已修复，请查看2.14.3-b2版本
