### ISSUE TITLE
加载微信 API 证书出错

### ISSUE THREAD

**Issue by yeliulee** [egzosn/pay-java-parent#85]
![image](https://user-images.githubusercontent.com/49977991/149308541-2666fa65-f766-4abc-ac56-b72b5a66466e.png)
![image](https://user-images.githubusercontent.com/49977991/149308613-6bb0fe6c-0dde-4d81-b1e3-7b20c4179a4c.png)
![image](https://user-images.githubusercontent.com/49977991/149308704-bd7af85f-2459-45c8-8254-c840fe3cbfe7.png)

出错原因：path 已经是 "classpath:" 开头（已实测, 已解决）

大佬能不能加个判断，谢谢，方便后面的人

**Comment by egzosn** [comment]
你的意思是识别classpath:开头的就是class_path类型，这个需求嘛

**Comment by yeliulee** [comment]
> 你的意思是识别classpath:开头的就是class_path类型，这个需求嘛

是的
