### ISSUE TITLE
接入微信V3支付出现空指针问题

### ISSUE THREAD

**Issue by wangchaoyu1992** [egzosn/pay-java-parent#86]
微信V3支付 初始化   WxPayService 的时候 wxParameterStructure 没有初始化
protected void initAfter() {
        payConfigStorage.setPartner(StringUtils.isNotEmpty(payConfigStorage.getSubMchId()));
        new Thread(() -> {
            payConfigStorage.loadCertEnvironment();
            wxParameterStructure = new WxParameterStructure(payConfigStorage);
            getAssistService();
        }).start();

    }

 public JSONObject unifiedOrder(PayOrder order) {

        //统一下单
       //wxParameterStructure == null ，报空指针
        Map<String, Object> parameters =  wxParameterStructure.initPartner(null);
       ;

**Comment by egzosn** [comment]
已修复
