### ISSUE TITLE
paypal /v2/checkout/orders/{order_id}/capture 什么时候执行

### ISSUE THREAD

**Issue by LuckDIY** [egzosn/pay-java-parent#98]
你好，请问 v2/checkout/orders 创建订单时 returnUrl 调用接口里应该放扣款的代码(/v2/checkout/orders/{order_id}/capture)吗？
![image](https://user-images.githubusercontent.com/49643408/202844373-c2819072-e2d4-45fc-8b7c-81b2dcf2ae46.png)
目前没有看到这个在什么地方you有调用？

**Comment by egzosn** [comment]
回调的时候自己调用来着
